function numberToCurrency(a){return Math.round(a*100)/100}function nullDataHandler(){}function errorHandler(a,b){alert("There was an error (code "+b.code+"): "+b.message);return false}
function updateGrandTotal(a,b){a=b.rows.item(0);document.getElementById("total").textContent=numberToCurrency((a.total||0)/100);document.getElementById("daily_average").textContent=numberToCurrency((a.total||0)/100/numberOfDays);document.getElementById("weekly_average").textContent=numberToCurrency((a.total||0)/100/numberOfWeeks)}function updateWeeklyTotal(a,b){a=b.rows.item(0);document.getElementById("weekly_total").textContent=numberToCurrency((a.total||0)/100)}
function updateMonthlyTotal(a,b){a=b.rows.item(0);document.getElementById("monthly_total").textContent=numberToCurrency((a.total||0)/100)}function updateBreakdowns(a,b){a=document.getElementById("breakdowns");a.innerHTML="";for(var c=0;c<b.rows.length;c++){var d=b.rows.item(c),f=document.createElement("tr");a.appendChild(f);if(c%2==1)f.className="even";f.innerHTML="<th>"+d.spent_at_date+"</th><td>&pound;"+numberToCurrency(d.total/100)+"</td>"}}
function updateAverages(a,b){for(a=0;a<b.rows.length;a++){var c=b.rows.item(a);switch(c.weekday){case "0":document.getElementById("sunday").textContent=numberToCurrency(c.total/100/numberOfWeeks);break;case "1":document.getElementById("monday").textContent=numberToCurrency(c.total/100/numberOfWeeks);break;case "2":document.getElementById("tuesday").textContent=numberToCurrency(c.total/100/numberOfWeeks);break;case "3":document.getElementById("wednesday").textContent=numberToCurrency(c.total/100/numberOfWeeks);
break;case "4":document.getElementById("thursday").textContent=numberToCurrency(c.total/100/numberOfWeeks);break;case "5":document.getElementById("friday").textContent=numberToCurrency(c.total/100/numberOfWeeks);break;case "6":document.getElementById("saturday").textContent=numberToCurrency(c.total/100/numberOfWeeks);break}}}
function setNumberOfDaysAndWeeks(a,b){a=b.rows.item(0).oldest.split(/\D/);a=new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5]);numberOfDays=Math.ceil((new Date-a)/864E5);numberOfWeeks=Math.ceil(numberOfDays/7)}
function updatePage(a){a.executeSql("SELECT MIN(spent_at) AS oldest FROM spends",[],setNumberOfDaysAndWeeks,errorHandler);a.executeSql("SELECT SUM(amount) AS total FROM spends",[],updateGrandTotal,errorHandler);a.executeSql("SELECT SUM(amount) AS total FROM spends WHERE spent_at > datetime('now', '-7 days', 'weekday 1', 'start of day')",[],updateWeeklyTotal,errorHandler);a.executeSql("SELECT SUM(amount) AS total FROM spends WHERE spent_at > datetime('now', 'start of month', 'start of day')",[],updateMonthlyTotal,
errorHandler);a.executeSql("SELECT spent_at, date(spent_at) AS spent_at_date, SUM(amount) AS total FROM spends GROUP BY spent_at_date",[],updateBreakdowns,errorHandler);a.executeSql("SELECT strftime('%w', spent_at) AS weekday, SUM(amount) AS total FROM spends GROUP BY weekday",[],updateAverages,errorHandler)}
function addSpend(){var a=document.getElementById("description"),b=a.value,c=document.getElementById("amount"),d=c.value;if(parseFloat(d)>0){var f=d*100;db.transaction(function(g){g.executeSql("INSERT INTO spends (amount, description) VALUES (?, ?)",[f,b],updatePage,errorHandler)})}c.value="";a.value="";return false}if(window.openDatabase)try{var db=openDatabase("spendthrift","1.0","Spendthrift Database",65536),numberOfWeeks=1,numberOfDays=1}catch(e){alert("Error opening database "+e)}else alert("Spendthrift is not supported by your current browser.");
db.transaction(function(a){a.executeSql("CREATE TABLE IF NOT EXISTS spends (id INTEGER PRIMARY KEY, amount INTEGER NOT NULL, description NVARCHAR, spent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);",[],nullDataHandler,errorHandler)});db.transaction(function(a){updatePage(a)});
