function numberToCurrency(b,c){c||(c=2);return Math.round(b*Math.pow(10,c))/Math.pow(10,c)}function nullDataHandler(){}function errorHandler(b,c){alert("There was an error (code "+c.code+"): "+c.message);return false}
function updateGrandTotal(b,c){var a=c.rows.item(0);document.getElementById("total").textContent=numberToCurrency((a.total||0)/100);document.getElementById("daily_average").textContent=numberToCurrency((a.total||0)/100/numberOfDays);document.getElementById("weekly_average").textContent=numberToCurrency((a.total||0)/100/numberOfWeeks)}function updateWeeklyTotal(b,c){var a=c.rows.item(0);document.getElementById("weekly_total").textContent=numberToCurrency((a.total||0)/100)}
function updateMonthlyTotal(b,c){var a=c.rows.item(0);document.getElementById("monthly_total").textContent=numberToCurrency((a.total||0)/100)}function updateLastMonthTotal(b,c){var a=c.rows.item(0);document.getElementById("last_month").textContent=numberToCurrency((a.total||0)/100);a=parseFloat(document.getElementById("last_month").textContent)-parseFloat(document.getElementById("monthly_total").textContent);document.getElementById("month_delta").textContent=numberToCurrency(a)}
function updateBreakdowns(b,c){var a=document.getElementById("breakdowns");a.innerHTML="";for(var g=0;g<c.rows.length;g++){var n=c.rows.item(g),f=document.createElement("tr");a.appendChild(f);if(g%2==1)f.className="even";f.innerHTML="<th>"+n.spent_at_date+"</th><td>&pound;"+numberToCurrency(n.total/100)+"</td>"}}
function updateAverages(b,c){for(var a=0;a<c.rows.length;a++){var g=c.rows.item(a);switch(g.weekday){case "0":document.getElementById("sunday").textContent=numberToCurrency(g.total/100/numberOfWeeks);break;case "1":document.getElementById("monday").textContent=numberToCurrency(g.total/100/numberOfWeeks);break;case "2":document.getElementById("tuesday").textContent=numberToCurrency(g.total/100/numberOfWeeks);break;case "3":document.getElementById("wednesday").textContent=numberToCurrency(g.total/100/
numberOfWeeks);break;case "4":document.getElementById("thursday").textContent=numberToCurrency(g.total/100/numberOfWeeks);break;case "5":document.getElementById("friday").textContent=numberToCurrency(g.total/100/numberOfWeeks);break;case "6":document.getElementById("saturday").textContent=numberToCurrency(g.total/100/numberOfWeeks);break}}}
function exportSpends(){var b="mailto:?subject=Spendthrift Export&body=[";db.transaction(function(c){c.executeSql("SELECT * FROM spends",[],function(a,g){for(var n=g.rows.length,f=0;f<n;f++){var r=g.rows.item(f);b+=JSON.stringify(r);if(f!=n-1)b+=", "}window.location=b+"]"},errorHandler)});return false}
function setNumberOfDaysAndWeeks(b,c){if(c.rows.item(0).oldest){var a=c.rows.item(0).oldest.split(/\D/);a=new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5]);numberOfDays=Math.ceil((new Date-a)/864E5);numberOfWeeks=Math.ceil(numberOfDays/7)}}
function updatePage(b){b.executeSql("SELECT MIN(spent_at) AS oldest FROM spends",[],setNumberOfDaysAndWeeks,errorHandler);b.executeSql("SELECT SUM(amount) AS total FROM spends",[],updateGrandTotal,errorHandler);b.executeSql("SELECT SUM(amount) AS total FROM spends WHERE spent_at > datetime('now', '-7 days', 'weekday 1', 'start of day')",[],updateWeeklyTotal,errorHandler);b.executeSql("SELECT SUM(amount) AS total FROM spends WHERE spent_at > datetime('now', 'start of month', 'start of day')",[],updateMonthlyTotal,
errorHandler);b.executeSql("SELECT SUM(amount) AS total FROM spends WHERE spent_at > datetime('now', '-1 month', 'start of month', 'start of day') AND spent_at < datetime('now', 'start of month', 'start of day')",[],updateLastMonthTotal,errorHandler);b.executeSql("SELECT spent_at, date(spent_at) AS spent_at_date, SUM(amount) AS total FROM spends GROUP BY spent_at_date",[],updateBreakdowns,errorHandler);b.executeSql("SELECT strftime('%w', spent_at) AS weekday, SUM(amount) AS total FROM spends GROUP BY weekday",
[],updateAverages,errorHandler)}function addSpend(){var b=document.getElementById("description"),c=b.value,a=document.getElementById("amount"),g=a.value;if(parseFloat(g)>0){var n=g*100;db.transaction(function(f){f.executeSql("INSERT INTO spends (amount, description) VALUES (?, ?)",[n,c],updatePage,errorHandler)})}a.value="";b.value="";return false}
if(window.openDatabase)try{var db=openDatabase("spendthrift","1.0","Spendthrift Database",65536),numberOfWeeks=1,numberOfDays=1}catch(e){alert("Error opening database "+e)}else alert("Spendthrift is not supported by your current browser.");db.transaction(function(b){b.executeSql("CREATE TABLE IF NOT EXISTS spends (id INTEGER PRIMARY KEY, amount INTEGER NOT NULL, description NVARCHAR, spent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);",[],nullDataHandler,errorHandler)});db.transaction(function(b){updatePage(b)});if(!this.JSON)this.JSON={};
(function(){function b(h){return h<10?"0"+h:h}function c(h){n.lastIndex=0;return n.test(h)?'"'+h.replace(n,function(l){var i=s[l];return typeof i==="string"?i:"\\u"+("0000"+l.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+h+'"'}function a(h,l){var i,j,m,p,o=f,k,d=l[h];if(d&&typeof d==="object"&&typeof d.toJSON==="function")d=d.toJSON(h);if(typeof q==="function")d=q.call(l,h,d);switch(typeof d){case "string":return c(d);case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);
case "object":if(!d)return"null";f+=r;k=[];if(Object.prototype.toString.apply(d)==="[object Array]"){p=d.length;for(i=0;i<p;i+=1)k[i]=a(i,d)||"null";m=k.length===0?"[]":f?"[\n"+f+k.join(",\n"+f)+"\n"+o+"]":"["+k.join(",")+"]";f=o;return m}if(q&&typeof q==="object"){p=q.length;for(i=0;i<p;i+=1){j=q[i];if(typeof j==="string")if(m=a(j,d))k.push(c(j)+(f?": ":":")+m)}}else for(j in d)if(Object.hasOwnProperty.call(d,j))if(m=a(j,d))k.push(c(j)+(f?": ":":")+m);m=k.length===0?"{}":f?"{\n"+f+k.join(",\n"+f)+
"\n"+o+"}":"{"+k.join(",")+"}";f=o;return m}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
n=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,r,s={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},q;if(typeof JSON.stringify!=="function")JSON.stringify=function(h,l,i){var j;r=f="";if(typeof i==="number")for(j=0;j<i;j+=1)r+=" ";else if(typeof i==="string")r=i;if((q=l)&&typeof l!=="function"&&(typeof l!=="object"||typeof l.length!=="number"))throw new Error("JSON.stringify");return a("",
{"":h})};if(typeof JSON.parse!=="function")JSON.parse=function(h,l){function i(m,p){var o,k,d=m[p];if(d&&typeof d==="object")for(o in d)if(Object.hasOwnProperty.call(d,o)){k=i(d,o);if(k!==undefined)d[o]=k;else delete d[o]}return l.call(m,p,d)}var j;h=String(h);g.lastIndex=0;if(g.test(h))h=h.replace(g,function(m){return"\\u"+("0000"+m.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(h.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+h+")");return typeof l==="function"?i({"":j},""):j}throw new SyntaxError("JSON.parse");}})();
