function numberToCurrency(a){return Math.round(a*100)/100}function nullDataHandler(){}function errorHandler(a,c){alert("There was an error (code "+c.code+"): "+c.message);return false}
function updateGrandTotal(a,c){a=c.rows.item(0);document.getElementById("total").textContent=numberToCurrency((a.total||0)/100);document.getElementById("daily_average").textContent=numberToCurrency((a.total||0)/100/numberOfDays);document.getElementById("weekly_average").textContent=numberToCurrency((a.total||0)/100/numberOfWeeks)}function updateWeeklyTotal(a,c){a=c.rows.item(0);document.getElementById("weekly_total").textContent=numberToCurrency((a.total||0)/100)}
function updateMonthlyTotal(a,c){a=c.rows.item(0);document.getElementById("monthly_total").textContent=numberToCurrency((a.total||0)/100)}function updateBreakdowns(a,c){a=document.getElementById("breakdowns");a.innerHTML="";for(var d=0;d<c.rows.length;d++){var m=c.rows.item(d),k=document.createElement("tr");a.appendChild(k);if(d%2==1)k.className="even";k.innerHTML="<th>"+m.spent_at_date+"</th><td>&pound;"+numberToCurrency(m.total/100)+"</td>"}}
function updateAverages(a,c){for(a=0;a<c.rows.length;a++){var d=c.rows.item(a);switch(d.weekday){case "0":document.getElementById("sunday").textContent=numberToCurrency(d.total/100/numberOfWeeks);break;case "1":document.getElementById("monday").textContent=numberToCurrency(d.total/100/numberOfWeeks);break;case "2":document.getElementById("tuesday").textContent=numberToCurrency(d.total/100/numberOfWeeks);break;case "3":document.getElementById("wednesday").textContent=numberToCurrency(d.total/100/numberOfWeeks);
break;case "4":document.getElementById("thursday").textContent=numberToCurrency(d.total/100/numberOfWeeks);break;case "5":document.getElementById("friday").textContent=numberToCurrency(d.total/100/numberOfWeeks);break;case "6":document.getElementById("saturday").textContent=numberToCurrency(d.total/100/numberOfWeeks);break}}}
function exportSpends(){var a="mailto:?subject=Spendthrift Export&body=[";db.transaction(function(c){c.executeSql("SELECT * FROM spends",[],function(d,m){d=m.rows.length;for(var k=0;k<d;k++){var i=m.rows.item(k);a+=JSON.stringify(i);if(k!=d-1)a+=", "}window.location=a+"]"},errorHandler)});return false}
function setNumberOfDaysAndWeeks(a,c){if(c.rows.item(0).oldest){a=c.rows.item(0).oldest.split(/\D/);a=new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5]);numberOfDays=Math.ceil((new Date-a)/864E5);numberOfWeeks=Math.ceil(numberOfDays/7)}}
function updatePage(a){a.executeSql("SELECT MIN(spent_at) AS oldest FROM spends",[],setNumberOfDaysAndWeeks,errorHandler);a.executeSql("SELECT SUM(amount) AS total FROM spends",[],updateGrandTotal,errorHandler);a.executeSql("SELECT SUM(amount) AS total FROM spends WHERE spent_at > datetime('now', '-7 days', 'weekday 1', 'start of day')",[],updateWeeklyTotal,errorHandler);a.executeSql("SELECT SUM(amount) AS total FROM spends WHERE spent_at > datetime('now', 'start of month', 'start of day')",[],updateMonthlyTotal,
errorHandler);a.executeSql("SELECT spent_at, date(spent_at) AS spent_at_date, SUM(amount) AS total FROM spends GROUP BY spent_at_date",[],updateBreakdowns,errorHandler);a.executeSql("SELECT strftime('%w', spent_at) AS weekday, SUM(amount) AS total FROM spends GROUP BY weekday",[],updateAverages,errorHandler)}
function addSpend(){var a=document.getElementById("description"),c=a.value,d=document.getElementById("amount"),m=d.value;if(parseFloat(m)>0){var k=m*100;db.transaction(function(i){i.executeSql("INSERT INTO spends (amount, description) VALUES (?, ?)",[k,c],updatePage,errorHandler)})}d.value="";a.value="";return false}if(window.openDatabase)try{var db=openDatabase("spendthrift","1.0","Spendthrift Database",65536),numberOfWeeks=1,numberOfDays=1}catch(e){alert("Error opening database "+e)}else alert("Spendthrift is not supported by your current browser.");
db.transaction(function(a){a.executeSql("CREATE TABLE IF NOT EXISTS spends (id INTEGER PRIMARY KEY, amount INTEGER NOT NULL, description NVARCHAR, spent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);",[],nullDataHandler,errorHandler)});db.transaction(function(a){updatePage(a)});if(!this.JSON)this.JSON={};
(function(){function a(b){return b<10?"0"+b:b}function c(b){k.lastIndex=0;return k.test(b)?'"'+b.replace(k,function(g){var h=r[g];return typeof h==="string"?h:"\\u"+("0000"+g.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function d(b,g){var h,l,o=i,j,f=g[b];if(f&&typeof f==="object"&&typeof f.toJSON==="function")f=f.toJSON(b);if(typeof p==="function")f=p.call(g,b,f);switch(typeof f){case "string":return c(f);case "number":return isFinite(f)?String(f):"null";case "boolean":case "null":return String(f);case "object":if(!f)return"null";
i+=q;j=[];if(Object.prototype.toString.apply(f)==="[object Array]"){l=f.length;for(b=0;b<l;b+=1)j[b]=d(b,f)||"null";g=j.length===0?"[]":i?"[\n"+i+j.join(",\n"+i)+"\n"+o+"]":"["+j.join(",")+"]";i=o;return g}if(p&&typeof p==="object"){l=p.length;for(b=0;b<l;b+=1){h=p[b];if(typeof h==="string")if(g=d(h,f))j.push(c(h)+(i?": ":":")+g)}}else for(h in f)if(Object.hasOwnProperty.call(f,h))if(g=d(h,f))j.push(c(h)+(i?": ":":")+g);g=j.length===0?"{}":i?"{\n"+i+j.join(",\n"+i)+"\n"+o+"}":"{"+j.join(",")+"}";
i=o;return g}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var m=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
k=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,i,q,r={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},p;if(typeof JSON.stringify!=="function")JSON.stringify=function(b,g,h){var l;q=i="";if(typeof h==="number")for(l=0;l<h;l+=1)q+=" ";else if(typeof h==="string")q=h;if((p=g)&&typeof g!=="function"&&(typeof g!=="object"||typeof g.length!=="number"))throw new Error("JSON.stringify");return d("",
{"":b})};if(typeof JSON.parse!=="function")JSON.parse=function(b,g){function h(l,o){var j,f,n=l[o];if(n&&typeof n==="object")for(j in n)if(Object.hasOwnProperty.call(n,j)){f=h(n,j);if(f!==undefined)n[j]=f;else delete n[j]}return g.call(l,o,n)}b=String(b);m.lastIndex=0;if(m.test(b))b=b.replace(m,function(l){return"\\u"+("0000"+l.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){b=eval("("+b+")");return typeof g==="function"?h({"":b},""):b}throw new SyntaxError("JSON.parse");}})();
